language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.1
  - jruby-head
  - rbx-2
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
  fast_finish: true
before_install:
  - gem update bundler
